### ISSUE TITLE
js에선 함수명에 보통 camelCase를 사용합니다.

### ISSUE THREAD

**Issue by niceaji** [nhwa/start-fe#1]
https://github.com/nhwa/start-fe/blob/7f86972df1edb279d6586ba11f0d59cea5959818/05/quiz4.html#L54

https://m.blog.naver.com/PostView.nhn?blogId=playcodingacademy&logNo=221317135750&proxyReferer=https:%2F%2Fwww.google.com%2F

파스칼케이스는 클래스명에 사용하구요 .
참고하세요

**Comment by nhwa** [comment]
감사합니다! 앞으로 참고해서 코드 작성하겠습니다!
